import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
    "./types/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        ink: 'var(--ink)',
        cream: 'var(--cream)',
        'amber-soft': '#FEF3E2',
        brand: { DEFAULT: '#F59E0B', light: '#FBBF24', dark: '#D97706' },
        surface: { DEFAULT: '#15161E', deep: '#0B0C12' },
        primary: {
          50: '#FFFBEB',
          100: '#FEF3C7',
          200: '#FDE68A',
          300: '#FCD34D',
          400: '#FBBF24',
          500: '#F59E0B',
          600: '#D97706',
          700: '#B45309',
          800: '#92400E',
          900: '#78350F',
          DEFAULT: "#F59E0B",
          light: "#FBBF24",
          dark: "#D97706",
        },
        dark: {
          50: '#4B5563',
          100: '#374151',
          200: '#2D3748',
          300: '#1F2937',
          400: '#1A2332',
          500: '#1A1F2E',
          600: '#161B29',
          700: '#111827',
          800: '#0D1520',
          900: '#09101A',
          DEFAULT: "#1F2937",
          mid: "#374151",
        },
        neutral: {
          DEFAULT: "#FFFFFF",
          card: "#F3F4F6",
          placeholder: "#9CA3AF",
          text: "#374151",
        },
        success: "#059669",
        error: "#DC2626",
        warning: "#F59E0B",
      },
      fontFamily: {
        sans: ["Outfit", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Outfit", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
