export const authIcons = {
  back: 'CaretLeft',
  close: 'X',
  chevronRight: 'CaretRight',
  check: 'Check',
  lock: 'Lock',
  shield: 'ShieldCheck',
  warning: 'Warning',
  phone: 'Phone',
  email: 'EnvelopeSimple',
  user: 'User',
  wrench: 'Wrench',
  eye: 'Eye',
  eyeSlash: 'EyeSlash',
  clock: 'Clock',
  checkCircle: 'CheckCircle',
  info: 'Info',
  hourglass: 'HourglassSimple',
  bell: 'Bell',
  globe: 'Globe',
  building: 'Building',
} as const
