export const v3 = {
  colors: {
    ink: '#000000',
    paper: '#FFFFFF',
    canvas: '#F7F7F7',
    canvasAlt: '#F6F6F6',
    line: '#E5E5E5',
    lineSubtle: '#E3E3E3',

    amber: '#F5A623',
    amberSoft: '#FFF1D2',
    amberSoftAlt: '#FFF3D9',
    amberDark: '#9A6000',
    amberTint: 'rgba(245,166,35,0.12)',
    amberBg: '#FFF8E8',

    success: '#06C167',
    info: '#276EF1',
    infoSoft: '#EAF0FF',
    error: '#E11900',

    textPrimary: '#000000',
    textSecondary: '#6F6F6F',
    textMuted: '#8A8A8A',
    textPlaceholder: '#B0B0B0',
    textLight: '#B9B9B9',

    surfaceWhite: '#FFFFFF',
    surfaceGray: '#F1F1F1',
    surfaceCanvas: '#F7F7F7',
  },

  typography: {
    brand: { fontSize: 13, fontWeight: '900' as const, fontFamily: 'Outfit_900Black' },
    hero: { fontSize: 30, fontWeight: '900' as const, fontFamily: 'Outfit_900Black' },
    h1: { fontSize: 28, fontWeight: '900' as const, fontFamily: 'Outfit_900Black' },
    h2: { fontSize: 27, fontWeight: '900' as const, fontFamily: 'Outfit_900Black' },
    h3: { fontSize: 26, fontWeight: '900' as const, fontFamily: 'Outfit_900Black' },
    h4: { fontSize: 25, fontWeight: '900' as const, fontFamily: 'Outfit_900Black' },
    h5: { fontSize: 24, fontWeight: '900' as const, fontFamily: 'Outfit_900Black' },
    title: { fontSize: 17, fontWeight: '850' as const, fontFamily: 'Outfit_800ExtraBold' },
    subtitle: { fontSize: 11, fontWeight: '600' as const, fontFamily: 'Outfit_500Medium' },
    bodyLarge: { fontSize: 13.5, fontWeight: '850' as const, fontFamily: 'Outfit_800ExtraBold' },
    body: { fontSize: 12, fontWeight: '600' as const, fontFamily: 'Outfit_500Medium' },
    bodyBold: { fontSize: 12, fontWeight: '800' as const, fontFamily: 'Outfit_700Bold' },
    caption: { fontSize: 11, fontWeight: '600' as const, fontFamily: 'Outfit_500Medium' },
    captionBold: { fontSize: 11, fontWeight: '800' as const, fontFamily: 'Outfit_700Bold' },
    label: { fontSize: 10, fontWeight: '800' as const, fontFamily: 'Outfit_700Bold' },
    labelMuted: { fontSize: 10, fontWeight: '600' as const, fontFamily: 'Outfit_500Medium' },
    small: { fontSize: 9, fontWeight: '600' as const, fontFamily: 'Outfit_500Medium' },
    smallBold: { fontSize: 9, fontWeight: '700' as const, fontFamily: 'Outfit_700Bold' },
  },

  spacing: {
    xxs: 2,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 18,
    xxl: 20,
    xxxl: 24,
    xxxxl: 32,
  },

  radius: {
    sm: 14,
    md: 15,
    lg: 16,
    xl: 20,
    xxl: 28,
    full: 9999,
  },

  components: {
    input: { height: 52, borderRadius: 14 },
    inputLarge: { height: 58, borderRadius: 15 },
    cta: { height: 54, borderRadius: 16 },
    ctaLarge: { height: 56, borderRadius: 16 },
    ctaSmall: { height: 50, borderRadius: 14 },
    otpStandard: { width: 54, height: 62, borderRadius: 16 },
    otpCompact: { width: 44, height: 52, borderRadius: 14 },
    avatar: { borderRadius: 18 },
    badge: { height: 24, borderRadius: 12 },
    listRow: { height: 58, borderRadius: 15 },
    listRowLarge: { height: 82, borderRadius: 15 },
    roleCard: { height: 150, borderRadius: 20 },
  },
} as const
