export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  Cleaning: [
    'clean', 'cleaning', 'cleanin', 'clene', 'clening', 'clane', 'cleaner',
    'maid', 'housekeeping', 'house clean', 'home clean', 'office clean',
    'vacuum', 'mop', 'moping', 'mopping', 'sweep', 'sweap', 'swiping',
    'dust', 'dusting', 'scrub', 'sanitize', 'sanitise', 'disinfect',
    'bathroom clean', 'kitchen clean', 'deep clean', 'move out clean',
    'piyadum', 'pirakshanaya', 'saaf', 'saaf karanna',
    'sutham', 'saabam', 'thoimai', 'sutham pannu',
    'සාෆ්', 'සාෆ් කරන්න', 'පිරිසිදු',
    'சுத்தம்', 'சுத்தம் பண்ணு',
  ],
  Plumbing: [
    'plumb', 'plumbing', 'plumber', 'plomber', 'plumbir',
    'pipe', 'pipes', 'piping', 'tap', 'taps', 'faucet',
    'leak', 'leaking', 'leakage', 'leck', 'leking',
    'drain', 'drainage', 'clogged', 'blocked drain', 'drain block',
    'toilet', 'toilet repair', 'toilet fix', 'flush',
    'sink', 'basin', 'water pipe', 'burst pipe',
    'water tank', 'overhead tank', 'tank clean',
    'jalagam', 'nol', 'pipe karanna',
    'kuzhal', 'pipe', 'thanni', 'kuzhal sudhi',
    'ජලගාම්', 'පයිප්ප', 'පයිප්ප ෆික්ස්',
    'குழாய்', 'பைப்', 'தண்ணீர் குழாய்',
  ],
  Electrical: [
    'elec', 'electrical', 'electrician', 'electric', 'electrik', 'elactrical',
    'wire', 'wiring', 'wirring', 'switch', 'socket', 'plug',
    'light', 'lighting', 'lamp', 'bulb', 'tube light', 'led',
    'fan', 'ceiling fan', 'exhaust fan', 'fan repair',
    'ac', 'aircon', 'air condition', 'air conditioning', 'cooler',
    'circuit', 'breaker', 'fuse', 'short circuit', 'power',
    'generator', 'inverter', 'stabilizer', 'voltage',
    'viduli', 'watt', 'bulb', 'current', 'light fix',
    'min', 'current', 'min velai',
    'විදුලි', 'විදුලි කාර්මික', 'වොට්', 'කරන්ට්',
    'மின்', 'மின் வேலை', 'கரண்ட்',
  ],
  Painting: [
    'paint', 'painting', 'paintir', 'painter', 'pencel', 'pinting',
    'color', 'coler', 'colouring', 'coloring', 'wall paint', 'ceiling paint',
    'interior', 'interior paint', 'exterior', 'exterior paint',
    'waterproof', 'waterproofing', 'texture', 'texture paint',
    'whitewash', 'white wash', 'emulsion', 'plaster',
    'brush', 'roller', 'spray paint', 'paint removal',
    'thaba', 'color', 'penn', 'thaba karanna',
    'varṇam', 'peynt', 'varṇam adi',
    'තබා', 'පෙන්', 'කලර්', 'තබා කරන්න',
    'வர்ணம்', 'பெயின்ட்', 'வர்ணம் அடி',
  ],
  'Repairs & Maintenance': [
    'repair', 'repairs', 'repare', 'repaer', 'fix', 'fixing',
    'maintenance', 'maintain', 'service', 'servicing',
    'handyman', 'handy man', 'odd jobs', 'oddjob',
    'furniture', 'furniture repair', 'cabinet', 'cupboard',
    'door repair', 'window repair', 'gate repair', 'lock',
    'wood work', 'carpentry', 'carpenter', 'wooden',
    'weld', 'welding', 'welder', 'metal',
    'aul', 'aluthwal', 'fix karanna', 'repair karanna',
    'repai', 'sudhi', 'repair pannu',
    'අලුත්වැඩ', 'ෆික්ස් කරන්න', 'රිපෙයාර්',
    'ரிப்பேர்', 'சூடி', 'ரிப்பேர் பண்ணு',
  ],
  Gardening: [
    'garden', 'gardening', 'gardan', 'graden', 'gardener', 'gardenir',
    'lawn', 'lawn mow', 'mowing', 'grass cut', 'grass cutting',
    'plant', 'plants', 'planting', 'tree', 'tree trim', 'pruning',
    'weed', 'weeding', 'weed removal', 'landscape', 'landscaping',
    'leaf', 'leaves', 'garden clean', 'yard', 'yard clean',
    'flower', 'flowers', 'hedge', 'hedge trim', 'fertilizer',
    'uayan', 'mal', 'gasa', 'vathto',
    'thottam', 'chedi', 'thottam velai',
    'උයන්', 'මල්', 'ගස්', 'වත්ත',
    'தோட்டம்', 'செடி', 'தோட்டம் வேலை',
  ],
  'Web Design': [
    'web', 'website', 'wab', 'wabsayt', 'websit',
    'web design', 'website design', 'web desing', 'wab desing',
    'web dev', 'web development', 'web developer',
    'ecommerce', 'e-com', 'online store', 'shopify',
    'graphic design', 'graphic', 'logo', 'logo design',
    'seo', 'digital marketing', 'social media',
    'app', 'mobile app', 'software',
    'domain', 'hosting', 'wordpress',
    'computer', 'it', 'tech', 'programming',
    'kanni', 'internet',
    'වෙබ්', 'වෙබ් ඩිසයින්', 'වෙබ් සයිට්',
    'வெப்', 'வெப் டிசைன்', 'கணினி',
  ],
  Assembly: [
    'assembly', 'assemble', 'assemb', 'set up', 'setup', 'setap',
    'furniture assembly', 'ikea', 'ikea assembly',
    'mount', 'mounting', 'mountin',
    'tv mount', 'tv mounting', 'wall mount',
    'curtain', 'curtain install', 'curtain mounting', 'blinds',
    'shelf', 'shelves', 'shelf install', 'rack', 'racking',
    'install', 'installation', 'installing',
    'sadeesi', 'fix karana', 'assemble karanna',
    'jodikka', 'kootu', 'fix pannu',
    'සාදීසි', 'අසෙම්බ්ලි', 'ෆික්ස් කරන',
    'ஜோடிக்க', 'கூட்டு', 'பிக்ஸ் பண்ணு',
  ],
  'Pest Control': [
    'pest', 'pest control', 'pestcontrol',
    'cockroach', 'cockroaches', 'roach', 'roaches',
    'ant', 'ants', 'termite', 'termites', 'white ant',
    'rat', 'rats', 'mouse', 'mice', 'rodent',
    'mosquito', 'mosquitoes', 'mosquito control', 'fogging',
    'bed bug', 'bed bugs', 'bug', 'bugs',
    'lizard', 'gecko', 'snake',
    'fumigate', 'fumigation', 'spray', 'insecticide',
    'කෘමි', 'කොක්ක්රෝච්', 'මදුරු',
    'பூச்சி', 'கரப்பான்', 'கொசு',
  ],
  'AC Service': [
    'ac', 'aircon', 'air condition', 'air conditioning', 'a/c',
    'ac service', 'ac repair', 'ac install', 'ac installation',
    'ac gas', 'gas fill', 'gas refill', 'refrigerant',
    'ac clean', 'ac cleaning', 'ac maintenance',
    'split ac', 'window ac', 'central ac', 'cassette ac',
    'cooler', 'air cooler',
    'esi', 'cooling',
    'ඒසී', 'ඒසී සර්විස්', 'ඒසී ෆික්ස්',
    'ஏசி', 'ஏசி சர்வீஸ்',
  ],
  'Water Tank Cleaning': [
    'tank', 'water tank', 'overhead tank', 'ground tank',
    'tank clean', 'tank cleaning', 'water tank clean',
    'tank service', 'tank wash',
    'water storage', 'tank maintenance',
    'ජල ටැංකි', 'ටැංකි ක්ලීනින්',
    'தண்ணீர் டேங்க்', 'டேங்க் சுத்தம்',
  ],
  Disinfection: [
    'disinfect', 'disinfection', 'sanitize', 'sanitization',
    'sanitise', 'sanitisation', 'sterilize', 'sterilization',
    'fog', 'fogging', 'fumigation',
    'covid', 'corona', 'virus', 'germs', 'bacteria',
    'antibacterial', 'antiviral', 'hygiene',
    'බැක්ටීරියා', 'විෂබීජ',
    'கிருமி', 'தொற்று',
  ],
  Moving: [
    'move', 'moving', 'mover', 'movers',
    'shifting', 'shift', 'relocation', 'relocate',
    'transport', 'transportation', 'vehicle',
    'pack', 'packing', 'packers', 'unpack',
    'loading', 'unloading', 'loading unloading',
    'home move', 'office move', 'house shifting',
    'van', 'lorry', 'truck', 'cab',
    'ගෙවල් වෙනස', 'ෂිෆ්ටින්',
    'வீடு மாற்றல்', 'ஷிப்டிங்',
  ],
}

export const CATEGORY_SLUGS: Record<string, string> = {
  Cleaning: 'cleaning',
  Plumbing: 'plumbing',
  Electrical: 'electrical',
  Painting: 'painting',
  'Repairs & Maintenance': 'repairs',
  Gardening: 'gardening',
  'Web Design': 'web-design',
  Assembly: 'assembly',
  'Pest Control': 'pest-control',
  'AC Service': 'ac-service',
  'Water Tank Cleaning': 'water-tank-cleaning',
  Disinfection: 'disinfection',
  Moving: 'moving',
}

export const DEFAULT_CATEGORY = 'Repairs & Maintenance'
