import { PRICING, getCategoryForSlug, DEFAULT_PRICING } from './pricing'

export interface SubTask {
  id: string
  name: string
  description: string
  priceRangeLKR: { min: number; max: number }
  priceRangeCAD: { min: number; max: number }
  estimatedTime: string
  difficulty: 'easy' | 'medium' | 'hard'
  tips: string[]
}

export interface CategorySubTasks {
  categoryId: string
  categoryName: string
  subTasks: SubTask[]
}

const SUB_TASKS: Record<string, SubTask[]> = {
  electrical: [
    {
      id: 'fix-switch-board',
      name: 'Fix / Replace Switch Board',
      description: 'Repair a faulty switch board, replace damaged switches, or upgrade to a new switch board. Covers standard 1-6 gang boards.',
      priceRangeLKR: { min: 800, max: 3500 },
      priceRangeCAD: { min: 80, max: 200 },
      estimatedTime: '1–2 hours',
      difficulty: 'medium',
      tips: ['Switch board type (modular vs old) affects price', 'Multiple switches = higher cost', 'Bring your own board or provider supplies?'],
    },
    {
      id: 'install-fan',
      name: 'Assemble & Install Ceiling Fan',
      description: 'Unbox, assemble, mount bracket, wire, and install a ceiling fan. Includes balancing blades and testing.',
      priceRangeLKR: { min: 1500, max: 4000 },
      priceRangeCAD: { min: 120, max: 250 },
      estimatedTime: '2–3 hours',
      difficulty: 'medium',
      tips: ['High ceilings may cost more', 'Existing wiring = cheaper', 'New wiring hole needed? Extra charge'],
    },
    {
      id: 'wiring-room',
      name: 'Full Room Wiring',
      description: 'Complete electrical wiring for one room — switches, sockets, light points, fan point. Conduit + cable work included.',
      priceRangeLKR: { min: 8000, max: 25000 },
      priceRangeCAD: { min: 500, max: 1200 },
      estimatedTime: '1–2 days',
      difficulty: 'hard',
      tips: ['Room size matters', 'New build vs renovation = different price', 'Materials may be separate'],
    },
    {
      id: 'install-light',
      name: 'Install Light Fixture',
      description: 'Mount and wire any light fixture — downlight, panel light, chandelier, tube light, or LED strip.',
      priceRangeLKR: { min: 500, max: 3000 },
      priceRangeCAD: { min: 60, max: 200 },
      estimatedTime: '30 min – 1.5 hours',
      difficulty: 'easy',
      tips: ['Heavy chandeliers cost more', 'Multiple lights in one visit = bulk discount', 'Smart light setup extra'],
    },
    {
      id: 'mcb-trip',
      name: 'Fix MCB / Circuit Breaker Tripping',
      description: 'Diagnose and fix why your circuit breaker keeps tripping. Check wiring faults, overloaded circuits, or faulty MCB.',
      priceRangeLKR: { min: 1000, max: 5000 },
      priceRangeCAD: { min: 100, max: 300 },
      estimatedTime: '1–3 hours',
      difficulty: 'medium',
      tips: ['Full diagnosis included', 'Parts extra if MCB needs replacing', 'Safety hazard — book urgent if sparking'],
    },
    {
      id: 'install-socket',
      name: 'Install Power Socket / Outlet',
      description: 'Add a new power socket or replace existing one. Includes back-box, wiring, and testing.',
      priceRangeLKR: { min: 600, max: 2500 },
      priceRangeCAD: { min: 70, max: 180 },
      estimatedTime: '30 min – 1 hour',
      difficulty: 'easy',
      tips: ['Outdoor/waterproof sockets cost more', 'New cable run = higher price', 'Double socket vs single'],
    },
    {
      id: 'apartment-wiring',
      name: 'Full Apartment Wiring',
      description: 'Complete wiring for an entire apartment — all rooms, kitchen, bathroom GFCI, distribution board.',
      priceRangeLKR: { min: 35000, max: 80000 },
      priceRangeCAD: { min: 2000, max: 5000 },
      estimatedTime: '3–5 days',
      difficulty: 'hard',
      tips: ['2-3 bedroom apartment', 'Materials usually separate', 'Inspection may be required'],
    },
  ],
  plumbing: [
    {
      id: 'fix-leak',
      name: 'Fix Leaking Pipe / Tap',
      description: 'Stop a leaking pipe joint, dripping faucet, or running toilet. Includes diagnosis and repair.',
      priceRangeLKR: { min: 500, max: 3000 },
      priceRangeCAD: { min: 80, max: 200 },
      estimatedTime: '30 min – 2 hours',
      difficulty: 'easy',
      tips: ['Hidden pipes = higher cost', 'Burst pipe = urgent pricing', 'Parts may be extra'],
    },
    {
      id: 'install-toilet',
      name: 'Install / Repair Toilet',
      description: 'Install a new toilet or repair existing — flapper, fill valve, wax seal, flush mechanism.',
      priceRangeLKR: { min: 2000, max: 8000 },
      priceRangeCAD: { min: 150, max: 400 },
      estimatedTime: '1–3 hours',
      difficulty: 'medium',
      tips: ['New install vs repair = different price', 'Wall-hung toilets cost more', 'Flange repair extra if needed'],
    },
    {
      id: 'unclog-drain',
      name: 'Unclog Drain / Sink',
      description: 'Clear blocked kitchen sink, bathroom drain, or floor drain. Uses snake/auger and chemical treatment.',
      priceRangeLKR: { min: 800, max: 3500 },
      priceRangeCAD: { min: 100, max: 250 },
      estimatedTime: '30 min – 2 hours',
      difficulty: 'easy',
      tips: ['Grease clogs need special treatment', 'Main line blockage = higher cost', 'Camera inspection extra'],
    },
    {
      id: 'install-faucet',
      name: 'Install / Replace Faucet',
      description: 'Remove old faucet, fit new one — kitchen mixer, bathroom sink, or shower faucet.',
      priceRangeLKR: { min: 1000, max: 4000 },
      priceRangeCAD: { min: 100, max: 250 },
      estimatedTime: '1–2 hours',
      difficulty: 'easy',
      tips: ['Mixer taps cost more to install', 'Old corroded fittings = extra work', 'Supply lines may need replacing'],
    },
    {
      id: 'water-tank',
      name: 'Water Tank Installation / Repair',
      description: 'Install overhead/underground water tank, float valve, or repair existing tank issues.',
      priceRangeLKR: { min: 3000, max: 12000 },
      priceRangeCAD: { min: 200, max: 600 },
      estimatedTime: '3–6 hours',
      difficulty: 'hard',
      tips: ['Rooftop access needed', 'Piping from tank = extra', 'Pump installation available'],
    },
    {
      id: 'pipe-relay',
      name: 'Relay / Replace Pipes',
      description: 'Replace old galvanized/CPVC pipes with new ones. Kitchen, bathroom, or whole house.',
      priceRangeLKR: { min: 5000, max: 25000 },
      priceRangeCAD: { min: 400, max: 1500 },
      estimatedTime: '1–3 days',
      difficulty: 'hard',
      tips: ['Material choice (CPVC, PEX, copper) affects price', 'Wall-breaking may be needed', 'Pressure test included'],
    },
  ],
  cleaning: [
    {
      id: 'deep-clean',
      name: 'Deep Home Cleaning',
      description: 'Full deep clean of house — floors, walls, windows, kitchen, bathrooms. Includes eco-friendly cleaning agents.',
      priceRangeLKR: { min: 3000, max: 12000 },
      priceRangeCAD: { min: 150, max: 400 },
      estimatedTime: '4–8 hours',
      difficulty: 'medium',
      tips: ['Number of rooms affects price', 'Move-in/move-out cleaning costs more', 'Pet hair extra?'],
    },
    {
      id: 'kitchen-clean',
      name: 'Kitchen Deep Clean',
      description: 'Intensive kitchen cleaning — stovetop, exhaust fan, cabinets inside-out, sink, floor degreasing.',
      priceRangeLKR: { min: 1500, max: 5000 },
      priceRangeCAD: { min: 80, max: 200 },
      estimatedTime: '2–4 hours',
      difficulty: 'medium',
      tips: ['Heavy grease = higher price', 'Appliance cleaning included', 'Cabinet organization extra'],
    },
    {
      id: 'bathroom-clean',
      name: 'Bathroom Deep Clean',
      description: 'Tile scrubbing, grout cleaning, toilet descaling, mirror, fixture polishing, floor mopping.',
      priceRangeLKR: { min: 800, max: 3000 },
      priceRangeCAD: { min: 60, max: 150 },
      estimatedTime: '1–2 hours',
      difficulty: 'easy',
      tips: ['Mold/stain removal extra', 'Multiple bathrooms = package deal', 'Eco-friendly products available'],
    },
    {
      id: 'carpet-clean',
      name: 'Carpet / Rug Cleaning',
      description: 'Steam cleaning or shampoo cleaning for carpets and rugs. Stain removal included.',
      priceRangeLKR: { min: 1000, max: 5000 },
      priceRangeCAD: { min: 80, max: 250 },
      estimatedTime: '2–4 hours',
      difficulty: 'medium',
      tips: ['Size per sq ft matters', 'Stain treatment extra', 'Drying time 24 hours'],
    },
    {
      id: 'window-clean',
      name: 'Window Cleaning (Full House)',
      description: 'Clean all windows inside and out, including frames and tracks. Multi-story available.',
      priceRangeLKR: { min: 1500, max: 6000 },
      priceRangeCAD: { min: 100, max: 300 },
      estimatedTime: '2–4 hours',
      difficulty: 'medium',
      tips: ['Number of windows affects price', 'High-rise extra', 'Screen cleaning included'],
    },
    {
      id: 'office-clean',
      name: 'Office / Commercial Cleaning',
      description: 'Regular or one-off office cleaning — desks, floors, restrooms, pantry, bins.',
      priceRangeLKR: { min: 5000, max: 20000 },
      priceRangeCAD: { min: 200, max: 800 },
      estimatedTime: '4–8 hours',
      difficulty: 'medium',
      tips: ['Monthly contracts cheaper', 'After-hours cleaning available', 'Waste disposal included'],
    },
  ],
  painting: [
    {
      id: 'paint-room',
      name: 'Paint One Room',
      description: 'Apply 2 coats of paint to one room — walls and ceiling. Surface prep (sanding, primer) included.',
      priceRangeLKR: { min: 4000, max: 12000 },
      priceRangeCAD: { min: 200, max: 500 },
      estimatedTime: '4–8 hours',
      difficulty: 'medium',
      tips: ['Dark colors need extra coat', 'Wall repair extra', 'Premium paint costs more'],
    },
    {
      id: 'paint-outer',
      name: 'Exterior House Painting',
      description: 'Full exterior painting — walls, trim, doors. Includes pressure washing and surface prep.',
      priceRangeLKR: { min: 15000, max: 50000 },
      priceRangeCAD: { min: 1000, max: 3000 },
      estimatedTime: '3–5 days',
      difficulty: 'hard',
      tips: ['Scaffolding may be extra', 'Weather dependent', 'Primer coat critical'],
    },
    {
      id: 'wallpaper',
      name: 'Wallpaper Installation',
      description: 'Measure, cut, and apply wallpaper to any wall. Includes surface prep and pattern matching.',
      priceRangeLKR: { min: 3000, max: 10000 },
      priceRangeCAD: { min: 200, max: 600 },
      estimatedTime: '3–6 hours',
      difficulty: 'medium',
      tips: ['Wallpaper material separate', 'Pattern matching = skill premium', 'Removal of old wallpaper extra'],
    },
    {
      id: 'paint-door',
      name: 'Paint Doors & Trim',
      description: 'Sand, prime, and paint interior doors, frames, and skirting boards.',
      priceRangeLKR: { min: 1000, max: 3500 },
      priceRangeCAD: { min: 80, max: 200 },
      estimatedTime: '2–4 hours',
      difficulty: 'easy',
      tips: ['Per door pricing available', 'Varnish/stain option', 'Multiple doors = discount'],
    },
  ],
  ac: [
    {
      id: 'ac-service',
      name: 'AC General Service',
      description: 'Full AC servicing — filter cleaning, gas check, coil cleaning, drain check. For split/window AC.',
      priceRangeLKR: { min: 1500, max: 4000 },
      priceRangeCAD: { min: 80, max: 180 },
      estimatedTime: '1–2 hours',
      difficulty: 'easy',
      tips: ['Regular service prevents breakdowns', 'Outdoor unit cleaning included', 'Annual contract available'],
    },
    {
      id: 'ac-install',
      name: 'AC Installation',
      description: 'Install a new split or window AC unit — bracket, piping, wiring, gas check, testing.',
      priceRangeLKR: { min: 5000, max: 15000 },
      priceRangeCAD: { min: 300, max: 800 },
      estimatedTime: '3–5 hours',
      difficulty: 'hard',
      tips: ['Outdoor unit placement matters', 'Long piping = extra cost', 'Electrical point may be needed'],
    },
    {
      id: 'ac-gas',
      name: 'AC Gas Refill',
      description: 'Diagnose gas leak, evacuate, and refill refrigerant gas (R22/R410a). Pressure test included.',
      priceRangeLKR: { min: 3000, max: 10000 },
      priceRangeCAD: { min: 200, max: 500 },
      estimatedTime: '1–3 hours',
      difficulty: 'medium',
      tips: ['Gas type affects price', 'Leak repair extra', 'Old AC may need full repair'],
    },
    {
      id: 'ac-repair',
      name: 'AC Repair / Diagnosis',
      description: 'Diagnose AC problems — not cooling, noise, leak, electrical fault. Fix or quote for parts.',
      priceRangeLKR: { min: 2000, max: 8000 },
      priceRangeCAD: { min: 150, max: 400 },
      estimatedTime: '1–3 hours',
      difficulty: 'medium',
      tips: ['Diagnostic fee may apply', 'Parts quoted separately', 'Warranty check'],
    },
  ],
  moving: [
    {
      id: 'small-move',
      name: 'Small Move (1 Room)',
      description: 'Move furniture and boxes from one room or small apartment. Includes loading, transport, unloading.',
      priceRangeLKR: { min: 3000, max: 8000 },
      priceRangeCAD: { min: 150, max: 400 },
      estimatedTime: '3–5 hours',
      difficulty: 'easy',
      tips: ['Box packing = extra', 'Fragile items special handling', 'Stair carry extra'],
    },
    {
      id: 'full-move',
      name: 'Full House Move',
      description: 'Complete household move — all rooms, kitchen, furniture. Includes wrapping, loading, transport, unloading.',
      priceRangeLKR: { min: 10000, max: 35000 },
      priceRangeCAD: { min: 500, max: 1500 },
      estimatedTime: '6–10 hours',
      difficulty: 'hard',
      tips: ['Packing materials separate', 'Distance affects price', 'Storage available'],
    },
    {
      id: 'furniture-shift',
      name: 'Single Furniture Shift',
      description: 'Move one piece of furniture — sofa, bed, wardrobe — within the same city.',
      priceRangeLKR: { min: 1500, max: 5000 },
      priceRangeCAD: { min: 80, max: 250 },
      estimatedTime: '1–3 hours',
      difficulty: 'easy',
      tips: ['Heavy items (piano) cost more', 'Floor level affects price', 'Assembly/disassembly extra'],
    },
    {
      id: 'office-move',
      name: 'Office / Commercial Move',
      description: 'Relocate office furniture, equipment, files. Includes IT equipment careful handling.',
      priceRangeLKR: { min: 15000, max: 50000 },
      priceRangeCAD: { min: 800, max: 3000 },
      estimatedTime: '1–2 days',
      difficulty: 'hard',
      tips: ['After-hours move available', 'IT setup extra', 'Labeling system recommended'],
    },
  ],
  gardening: [
    {
      id: 'lawn-mow',
      name: 'Lawn Mowing & Trimming',
      description: 'Mow, edge, and trim your lawn. Includes cleanup of clippings.',
      priceRangeLKR: { min: 1000, max: 3500 },
      priceRangeCAD: { min: 50, max: 150 },
      estimatedTime: '1–2 hours',
      difficulty: 'easy',
      tips: ['Lawn size affects price', 'Overgrown lawn = extra', 'Regular schedule discount'],
    },
    {
      id: 'garden-cleanup',
      name: 'Full Garden Cleanup',
      description: 'Clear weeds, prune bushes, rake leaves, trim hedges, remove green waste.',
      priceRangeLKR: { min: 2000, max: 8000 },
      priceRangeCAD: { min: 100, max: 350 },
      estimatedTime: '3–6 hours',
      difficulty: 'medium',
      tips: ['Waste removal extra', 'Overgrown gardens cost more', 'Disposal included?'],
    },
    {
      id: 'tree-trim',
      name: 'Tree Trimming / Cutting',
      description: 'Trim or cut trees — branches, dead wood, height reduction. Includes safety gear.',
      priceRangeLKR: { min: 3000, max: 15000 },
      priceRangeCAD: { min: 200, max: 800 },
      estimatedTime: '2–6 hours',
      difficulty: 'hard',
      tips: ['Tall trees = crane needed', 'Permission may be required', 'Stump removal extra'],
    },
  ],
  carpentry: [
    {
      id: 'furniture-assembly',
      name: 'Furniture Assembly',
      description: 'Assemble flat-pack or custom furniture — bed, wardrobe, shelf, desk, TV unit.',
      priceRangeLKR: { min: 1000, max: 5000 },
      priceRangeCAD: { min: 60, max: 250 },
      estimatedTime: '1–3 hours',
      difficulty: 'easy',
      tips: ['IKEA furniture = standard pricing', 'Custom = quote needed', 'Mounting on wall extra'],
    },
    {
      id: 'door-repair',
      name: 'Door Repair / Installation',
      description: 'Fix squeaky doors, replace hinges, install new door, adjust alignment.',
      priceRangeLKR: { min: 800, max: 4000 },
      priceRangeCAD: { min: 80, max: 200 },
      estimatedTime: '30 min – 2 hours',
      difficulty: 'easy',
      tips: ['New door install vs repair', 'Lock fitting extra', 'Frame repair may be needed'],
    },
    {
      id: 'shelf-install',
      name: 'Shelf / Cabinet Installation',
      description: 'Mount floating shelves, wall cabinets, kitchen cabinets. Includes drilling, bracket fitting.',
      priceRangeLKR: { min: 1000, max: 5000 },
      priceRangeCAD: { min: 80, max: 250 },
      estimatedTime: '1–3 hours',
      difficulty: 'easy',
      tips: ['Wall type affects drilling', 'Heavy items need anchors', 'Custom shelves = more'],
    },
    {
      id: 'custom-furniture',
      name: 'Custom Furniture Build',
      description: 'Build custom furniture to your specs — bookshelf, TV unit, kitchen island, bed frame.',
      priceRangeLKR: { min: 15000, max: 80000 },
      priceRangeCAD: { min: 500, max: 3000 },
      estimatedTime: '3–10 days',
      difficulty: 'hard',
      tips: ['Material choice affects price', 'Design consultation included', 'Delivery extra'],
    },
  ],
  pest: [
    {
      id: 'general-pest',
      name: 'General Pest Control',
      description: 'Spray treatment for ants, cockroaches, spiders, silverfish. Covers entire home interior.',
      priceRangeLKR: { min: 2000, max: 6000 },
      priceRangeCAD: { min: 100, max: 300 },
      estimatedTime: '1–2 hours',
      difficulty: 'easy',
      tips: ['Larger homes cost more', 'Pet-safe options available', 'Follow-up treatment included'],
    },
    {
      id: 'termite',
      name: 'Termite Treatment',
      description: 'Full termite treatment — drilling, injection, barrier treatment. For existing or prevention.',
      priceRangeLKR: { min: 8000, max: 30000 },
      priceRangeCAD: { min: 500, max: 1500 },
      estimatedTime: '4–8 hours',
      difficulty: 'hard',
      tips: ['House size affects price', 'Warranty (1-3 years)', 'Pre-treatment for new builds'],
    },
    {
      id: 'mosquito',
      name: 'Mosquito Fogging',
      description: 'Outdoor/indoor fogging for mosquito control. Covers garden and interior.',
      priceRangeLKR: { min: 2000, max: 8000 },
      priceRangeCAD: { min: 100, max: 350 },
      estimatedTime: '1–3 hours',
      difficulty: 'easy',
      tips: ['Area size affects price', 'Monthly plans available', 'After rain = reapply needed'],
    },
  ],
  renovation: [
    {
      id: 'bathroom-reno',
      name: 'Bathroom Renovation',
      description: 'Full bathroom renovation — tiling, fixture replacement, plumbing, waterproofing.',
      priceRangeLKR: { min: 50000, max: 200000 },
      priceRangeCAD: { min: 3000, max: 15000 },
      estimatedTime: '1–3 weeks',
      difficulty: 'hard',
      tips: ['Scope varies hugely', 'Design consultation included', 'Materials separate'],
    },
    {
      id: 'kitchen-reno',
      name: 'Kitchen Renovation',
      description: 'Kitchen remodel — cabinets, countertop, backsplash, plumbing, electrical, flooring.',
      priceRangeLKR: { min: 80000, max: 300000 },
      priceRangeCAD: { min: 5000, max: 25000 },
      estimatedTime: '2–4 weeks',
      difficulty: 'hard',
      tips: ['Custom cabinets cost more', 'Appliance fitting extra', 'Temporary kitchen needed'],
    },
    {
      id: 'room-reno',
      name: 'Single Room Renovation',
      description: 'Renovate one room — flooring, painting, ceiling, electrical, any structural changes.',
      priceRangeLKR: { min: 30000, max: 100000 },
      priceRangeCAD: { min: 2000, max: 8000 },
      estimatedTime: '1–2 weeks',
      difficulty: 'hard',
      tips: ['Scope depends on changes', 'Permits may be needed', 'Material choices matter'],
    },
  ],
  automotive: [
    {
      id: 'car-wash',
      name: 'Full Car Wash & Detail',
      description: 'Exterior wash, interior vacuum, dashboard polish, tire shine, window cleaning.',
      priceRangeLKR: { min: 1500, max: 5000 },
      priceRangeCAD: { min: 50, max: 200 },
      estimatedTime: '1–3 hours',
      difficulty: 'easy',
      tips: ['SUV/van cost more', 'Full detail vs basic wash', 'Scratch removal extra'],
    },
    {
      id: 'battery-replace',
      name: 'Car Battery Replacement',
      description: 'Test old battery, install new one, check charging system. All vehicle types.',
      priceRangeLKR: { min: 1000, max: 3000 },
      priceRangeCAD: { min: 50, max: 150 },
      estimatedTime: '30 min – 1 hour',
      difficulty: 'easy',
      tips: ['Battery cost separate', 'Japanese vs European car', 'Old battery disposal'],
    },
    {
      id: 'oil-change',
      name: 'Oil Change Service',
      description: 'Drain old oil, replace filter, refill with new oil. Engine check included.',
      priceRangeLKR: { min: 2000, max: 5000 },
      priceRangeCAD: { min: 80, max: 200 },
      estimatedTime: '30 min – 1 hour',
      difficulty: 'easy',
      tips: ['Synthetic oil costs more', 'Oil type affects price', 'Multi-point check included'],
    },
  ],
  repairs: [
    {
      id: 'appliance-repair',
      name: 'Home Appliance Repair',
      description: 'Fix washing machine, fridge, microwave, dryer, blender. Diagnosis + repair.',
      priceRangeLKR: { min: 1500, max: 8000 },
      priceRangeCAD: { min: 100, max: 400 },
      estimatedTime: '1–3 hours',
      difficulty: 'medium',
      tips: ['Brand matters', 'Parts quoted separately', 'Warranty check'],
    },
    {
      id: 'door-lock',
      name: 'Door Lock Repair / Replace',
      description: 'Fix jammed lock, replace lock mechanism, install new lock set.',
      priceRangeLKR: { min: 800, max: 4000 },
      priceRangeCAD: { min: 80, max: 250 },
      estimatedTime: '30 min – 1.5 hours',
      difficulty: 'easy',
      tips: ['Smart lock installation extra', 'Security grade matters', 'Key cutting extra'],
    },
    {
      id: 'furniture-repair',
      name: 'Furniture Repair',
      description: 'Fix wobbly chairs, broken drawers, loose joints, scratched surfaces.',
      priceRangeLKR: { min: 500, max: 5000 },
      priceRangeCAD: { min: 50, max: 250 },
      estimatedTime: '1–3 hours',
      difficulty: 'easy',
      tips: ['Wood type affects repair', 'Upholstery extra', 'Antique = careful handling'],
    },
    {
      id: 'window-repair',
      name: 'Window / Glass Repair',
      description: 'Fix broken window, replace glass pane, repair sliding mechanism.',
      priceRangeLKR: { min: 1000, max: 8000 },
      priceRangeCAD: { min: 80, max: 400 },
      estimatedTime: '1–3 hours',
      difficulty: 'medium',
      tips: ['Glass type affects price', 'Emergency board-up available', 'Frame repair extra'],
    },
  ],
  digital: [
    {
      id: 'website-build',
      name: 'Website Design & Build',
      description: 'Custom website — landing page, business site, or e-commerce. Responsive design included.',
      priceRangeLKR: { min: 25000, max: 150000 },
      priceRangeCAD: { min: 500, max: 5000 },
      estimatedTime: '1–4 weeks',
      difficulty: 'hard',
      tips: ['Number of pages affects price', 'E-commerce = more complex', 'Hosting extra'],
    },
    {
      id: 'logo-design',
      name: 'Logo Design',
      description: 'Custom logo design — 3 concepts, revisions, final files (PNG, SVG, AI).',
      priceRangeLKR: { min: 5000, max: 25000 },
      priceRangeCAD: { min: 100, max: 500 },
      estimatedTime: '3–7 days',
      difficulty: 'medium',
      tips: ['More concepts = higher price', 'Brand guide extra', 'Fast turnaround extra'],
    },
    {
      id: 'social-media',
      name: 'Social Media Setup & Management',
      description: 'Setup/optimize social media profiles, content calendar, posting schedule.',
      priceRangeLKR: { min: 10000, max: 40000 },
      priceRangeCAD: { min: 200, max: 1000 },
      estimatedTime: 'Ongoing monthly',
      difficulty: 'medium',
      tips: ['Monthly retainer', 'Content creation separate', 'Ad management extra'],
    },
  ],
}

export function getSubTasksForCategory(categoryId: string, categoryName?: string): SubTask[] {
  const directMatch = SUB_TASKS[categoryId]
  if (directMatch) return directMatch

  const name = (categoryName || '').toLowerCase()
  for (const [key, tasks] of Object.entries(SUB_TASKS)) {
    if (name.includes(key) || key.includes(name)) return tasks
  }

  return [
    {
      id: 'general-job',
      name: 'General Service',
      description: `Professional ${categoryName || 'general'} service. Describe your specific needs for an accurate quote.`,
      priceRangeLKR: { min: 2000, max: 10000 },
      priceRangeCAD: { min: 80, max: 400 },
      estimatedTime: '1–4 hours',
      difficulty: 'medium',
      tips: ['Describe your task for accurate pricing', 'Get multiple quotes', 'Check provider reviews'],
    },
  ]
}

export function getAllCategoriesSubTasks(): CategorySubTasks[] {
  return Object.entries(SUB_TASKS).map(([categoryId, subTasks]) => ({
    categoryId,
    categoryName: categoryId.charAt(0).toUpperCase() + categoryId.slice(1),
    subTasks,
  }))
}
