// Canonical role + permission vocabulary (moved verbatim from lib/admin-types.ts, Phase D).

export type AdminRole = 'SUPER_ADMIN' | 'MANAGER' | 'FINANCE' | 'USER_MANAGEMENT' | 'SUPPORT' | 'TECHNICAL'

export const ADMIN_ROLES: Record<AdminRole, { label: string; color: string; description: string }> = {
  SUPER_ADMIN: { label: 'Super Admin', color: 'purple', description: 'Full platform access, can reassign work queue' },
  MANAGER: { label: 'Manager', color: 'blue', description: 'Full read, reassign work, resolve escalations, manage work queue' },
  FINANCE: { label: 'Finance', color: 'green', description: 'Commission, wallets & settlements — settlement queue' },
  USER_MANAGEMENT: { label: 'User Management', color: 'orange', description: 'KYC review, user suspension & ban — KYC queue' },
  SUPPORT: { label: 'Support', color: 'yellow', description: 'Disputes, complaints & user tickets — dispute queue' },
  TECHNICAL: { label: 'Technical', color: 'cyan', description: 'Security audit, system health & error logs — system queue' },
}

export const ROLE_PERMISSIONS: Record<AdminRole, string[]> = {
  SUPER_ADMIN: [
    'dashboard:view',
    'users:view', 'users:edit', 'users:ban', 'users:suspend',
    'taskers:view', 'taskers:edit', 'taskers:ban', 'taskers:verify',
    'companies:view', 'companies:edit', 'companies:ban', 'companies:verify',
    'kyc:view', 'kyc:approve', 'kyc:reject',
    'jobs:view', 'jobs:manage', 'jobs:cancel',
    'commission:view', 'commission:manage', 'commission:config',
    'wallets:view', 'wallets:manage',
    'disputes:view', 'disputes:resolve',
    'cheating:view', 'cheating:action',
    'support:view', 'support:respond',
    'queue:view', 'queue:manage', 'queue:assign',
    'analytics:view',
    'admins:view', 'admins:create', 'admins:edit', 'admins:delete',
    'settings:view', 'settings:edit',
    'security:view', 'security:audit',
    'trust:view',
    'wishlist:view', 'wishlist:manage',
    'professions:read', 'professions:write',
    'credentials:read', 'credentials:write',
    'risk_events:read', 'risk_events:resolve',
    'pricing_config:read', 'pricing_config:write',
    'market_config:read', 'market_config:write',
    'audit:read',
    'subscriptions:view', 'subscriptions:manage',
    'real_estate:view', 'real_estate:manage',
  ],
  MANAGER: [
    'dashboard:view',
    'users:view', 'users:edit',
    'taskers:view', 'taskers:edit', 'taskers:verify',
    'companies:view', 'companies:edit', 'companies:verify',
    'jobs:view', 'jobs:manage',
    'disputes:view', 'disputes:resolve',
    'cheating:view', 'cheating:action',
    'queue:view', 'queue:manage', 'queue:assign',
    'analytics:view',
    'wishlist:view', 'wishlist:manage',
    'professions:read', 'professions:write',
    'credentials:read', 'credentials:write',
    'risk_events:read', 'risk_events:resolve',
    'trust:view',
    'audit:read',
    'subscriptions:view',
    'real_estate:view', 'real_estate:manage',
  ],
  FINANCE: [
    'dashboard:view',
    'users:view',
    'taskers:view',
    'companies:view',
    'commission:view', 'commission:manage', 'commission:config',
    'wallets:view', 'wallets:manage',
    'queue:view',
    'analytics:view',
    'pricing_config:read', 'pricing_config:write',
    'market_config:read', 'market_config:write',
    'audit:read',
    'subscriptions:view',
  ],
  USER_MANAGEMENT: [
    'dashboard:view',
    'users:view', 'users:edit', 'users:ban', 'users:suspend',
    'taskers:view', 'taskers:edit', 'taskers:ban', 'taskers:verify',
    'companies:view', 'companies:edit', 'companies:ban', 'companies:verify',
    'kyc:view', 'kyc:approve', 'kyc:reject',
    'cheating:view', 'cheating:action',
    'queue:view',
    'professions:read', 'professions:write',
    'credentials:read', 'credentials:write',
    'risk_events:read', 'risk_events:resolve',
    'trust:view',
    'audit:read',
    'real_estate:view',
  ],
  SUPPORT: [
    'dashboard:view',
    'users:view',
    'taskers:view',
    'companies:view',
    'disputes:view', 'disputes:resolve',
    'cheating:view',
    'support:view', 'support:respond',
    'kyc:view',
    'queue:view',
    'risk_events:read',
    'trust:view',
    'audit:read',
    'real_estate:view',
  ],
  TECHNICAL: [
    'dashboard:view',
    'security:view', 'security:audit',
    'trust:view',
    'queue:view',
    'analytics:view',
    'audit:read',
  ],
}
